config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  resources :posts

  post 'posts/unlock', to: 'posts#unlock'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  monetize :price_cents

  scope :locked, -> (number_of_posts) {where(is_locked: true).order(:created_at).first(number_of_posts)}

  def class_name
    self.is_locked ? "locked" : "unlocked"
  end

  def self.unlock(number_of_posts)
    locked_posts = Post.locked(number_of_posts)

    locked_posts.each do |post|
      post.is_locked = false
      post.save
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post_presenter ||= post_presenter
  end

  def create
    permitted_post_params = post_params
    permitted_post_params[:price_cents] = (100 * permitted_post_params[:price_cents].to_r).to_i
    @post = Post.create!(permitted_post_params)
    respond_to do |format|
      if @post.save
        format.html {redirect_to root_path}
        format.js
      else
        format.html {redirect_to root_path}
      end
    end
  end

  def unlock
    Post.unlock(params[:number_to_unlock].to_i)
    redirect_to 'posts/index'
  end

  private

  def post_presenter
    PostPresenter.new
  end

  def post_params
    @post_params ||= params.require(:post).permit(:text, :price_cents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PennyForYourThoughts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav>
        <%= render partial: 'auth/links' %>
      </nav>
      <header>
        <h1>A penny for your thoughts...</h1>
      </header>
      <%= notice %>
      <%= alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post <%= post.class_name %>">
  <% if post.is_locked %>
    <div class="post__text"><i class="fa fa-lock"></i> This post is locked. For <%= humanized_money_with_symbol(post.price) %> you can <a href="#">make a donation</a> to unlock it!</div>
  <% else %>
    <div class="post__text"><%= post.text %></div>
  <% end %>
  <div class="post__date">
    <%= post.created_at.strftime("Posted on %B %d, %Y") %></p>
  </div>
</div>

app/views/posts/_post_presenter.html.erb
<p><%= post_presenter.unlocked_post_count %> posts have been unlocked.</p>
<p><%= post_presenter.locked_post_count %> posts are waiting to be unlocked.</p>

<section id="post-feed">
  <% post_presenter.all_posts.each do |post| %>
    <%= render partial: 'post', locals: { post: post } %>
  <% end %>
</section>

app/views/posts/create.js.erb
$("#post-feed").prepend("<%= escape_javascript(render partial: 'post', locals: { post: @post }) %>");

app/views/posts/index.html.erb
<%= form_tag(posts_path, method: "post", remote: true) do %>
    <%= label_tag('post[text]', "Submit a Memory") %>
    <%= text_field_tag('post[text]') %>
    <%= label_tag('post[price_cents]', "Submit a Memory") %>
    <%= select_tag('post[price_cents]', "<option>0.99</option><option>4.99</option><option>99.99</option>".html_safe) %>
    <%= submit_tag("Submit") %>
<% end %>

<%= form_tag(posts_unlock_path, method: "post") do %>
    <%= label_tag('number_to_unlock', "Number of posts to unlock") %>
    <%= text_field_tag('number_to_unlock') %>
    <%= submit_tag("Submit") %>
<% end %>

<section id="post-presenter">
  <%= render partial: 'post_presenter', locals: { post_presenter: @post_presenter } %>
</section>